site_name: 'PCTOkay!'
site_description: 'Un''applicazione per gestire, cercare e selezionare ogni azienda disponibile con estrema facilità!'
site_author: 'Riccardo Sartori'
copyright: '2020 Riccardo Sartori'
repo_url: 'https://github.com/SartoRiccardo/pcto-anagrafe'

nav:
    - 'Project Summary': 'customer_requests.md'
    - 'Project Charter': 'project_charter.md'
    - 'Database': 'database.md'
    - 'Front-End': 'frontend.md'
    - 'Back-End': 'backend.md'
    - 'Modello Dati': 'data_models.md'

theme:
    name: readthedocs
